if: tag IS blank
git:
  depth: 1
sudo: required
language: node_js

node_js:
  - "8"
  - "9"
  - "10"

env:
  - CXX=g++-4.8

addons:
    chrome: stable

before_install:
  - npm install -g lerna@next yarn
  - ./scripts/if-opticss-dev.sh ./scripts/checkout-opticss.sh ../opticss
  - ./scripts/if-opticss-dev.sh ./scripts/link-to-opticss.js --file ../opticss

install:
  - lerna bootstrap --registry=https://registry.npmjs.org/

script: lerna run test

cache:
  yarn: true
  directories:
    - ~/.npm
